name: DynEconomy
version: 1.1
depend: [Vault, Towny, Essentials, TheNewEconomy]
author: NikeSwooosh
main: me.nikeswooosh.dyneconomy.DynEconomy
description: An economic simulation plugin
api-version: 1.16

commands:
    dyneconomy:
        aliases: [dyneco, de]
        description: The root DynEconomy command
        usage: |
            DynEconomy commands
            /dyneconomy info - Display the current state of the economy
            /dyneconomy sell - Sell a given amount of currency item to the server
            Admin commands
            /dyneconomy give [player] [amount] - Give a player a given quantity of money
            /dyneconomy take [player] [amount] - Take a given quantity of money from a player
            /dyneconomy resync - Resync plugin data with Towny and TNE

permissions:
    dyneco.player:
        default: true
    dyneco.admin:
        default: op
