name: DynEconomy
version: 1.0
depend: [Vault, Towny, Essentials, TheNewEconomy, QuickShop]
softdepend: [QuickShopAPI]
author: NikeSwooosh
main: me.nikeswooosh.dyneconomy.DynEconomy
description: Sell items to the server!
api-version: 1.16

commands:
  dyneconomy:
    aliases: [dyneco, de]
    description: this is the dynmoney command!

permissions:
    dyneco.player:
        default: true
    dyneco.admin:
        default: op
